apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: grayskull-fs
  namespace: "{{ ceph_namespace }}"
spec:
  failureDomain: host
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true

