ingress:
  enabled: true
  path: /
  hosts:
    - "ceph.{{ grayskull_domain }}"
  tls:
    - hosts:
        - "ceph.{{ grayskull_domain }}"
      secretName: ceph-gsp-tls
defaultStorage:
  enabled: true

csi:
  enableCephfsDriver: true
  enableRbdDriver: true
  forceCephFSKernelClient: false

hostpathRequiresPrivileged: true

tolerations:
  - key: "node-role.kubernetes.io/controlplane"
    operator: "Exists"
    effect: NoSchedule
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: NoExecute