apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dash-cert
  namespace: {{ ceph_namespace }}
spec:
  secretName: {{ ingress_secretName }}
  issuerRef:
    name: {{ grayskull_ca_issuer_name }}
    kind: ClusterIssuer
  dnsNames:
    - ceph.{{ grayskull_domain }}
