apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: {{ ceph_namespace }}
spec:
  cephVersion:
    image: {{ template_ceph_image }}:{{ template_ceph_image_version }}
    allowUnsupported: false
  dataDirHostPath: {{ ceph_data_dir }}
  mon:
    count: {{ ceph_mon_count }}
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    workers: 0
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/storage"
              operator: "Exists"
      tolerations:
      - key: "node-role.kubernetes.io/controlplane"
        operator: "Exists"
        effect: NoSchedule
      - key: "node-role.kubernetes.io/etcd"
        operator: "Exists"
        effect: NoExecute
  annotations:
  #resources:
  # The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
  #    mgr:
  #      limits:
  #        cpu: "500m"
  #        memory: "1024Mi"
  #      requests:
  #        cpu: "500m"
  #        memory: "1024Mi"
  # The above example requests/limits can also be added to the mon and osd components
  #    mon:
  #    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    #deviceFilter:
    #location:
    config:
    #- path: {{ ceph_data_dir }}
