server:
    port: 8888

spring:
    profiles:
        active: native, vault
    application:
        name: demosrv
    cloud:
        config:
            server:
                vault:
                    host: vault-stk
                    port: 8200
                    scheme: http
                    backend: secret
                    skipSslValidation: true
     
  
