- name: Ingress | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Ingress | Download chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_ingress_repo_url }} \
    --version {{ helm_ingress_chart_version }} \
    --destination {{ role_dir }} \
    --untar \
    {{ helm_ingress_image_name }}"  