- name: Ingress | Create namespace folder
  file:
    path: "{{ gitops_namespace_dir }}"
    state: directory
    mode: '0755'

- name: Ingress | Create releases folder
  file:
    path: "{{ gitops_release_dir }}"
    state: directory
    mode: '0755'

- name: Ingress | Create workloads folder
  file:
    path: "{{ gitops_workload_dir }}"
    state: directory
    mode: '0755'

- name: Ingress | Template namespace
  template:
    src: ingress-namespace.yml
    dest: "{{ gitops_namespace_dir }}/ingress-namespace.yml"

#---- Need to get the values into the release but don't want to duplicate them in case values file changes.

- name: Ingress | Template release
  template:
    src: gitops/release.yml
    dest: "{{ gitops_release_dir }}/release.yml"
