
- name: Ingress | Templates list
  set_fact:
    ingress_role_templates:
      - { name: namespace, file: ingress-namespace.yml, type: ns }

- name: Setup | Create subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: directory
    mode: '0755'

- name: Ingress | Template values file
  template:
    src: "ingress-values.yml"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/ingress-values.yml"

- name: Ingress | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.file }}"
  with_items: "{{ ingress_role_templates }}"
  register: ingress_role_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Ingress | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ ingress_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ ingress_role_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Ingress | Deploy chart
  helm_chart:
    name: "{{ helm_ingress_name }}"
    namespace: "{{ ingress_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: stable/nginx-ingress
    chart_version: 1.6.16
    path_to_values: "{{ grayskull_dir }}/{{ subfolder }}/ingress-values.yml"