- name: Ingress | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Ingress | Template values file
  template:
    src: "ingress-values.yml"
    dest: "{{ role_dir }}/ingress-values.yml"

- name: Ingress | Templates list
  set_fact:
    ingress_role_templates:
      - { file: ingress-namespace.yml }

- name: Ingress | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ ingress_role_templates }}"
  register: ingress_role_manifests

- name: Ingress | Apply manifests
  kube:
    namespace: "{{ ingress_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ ingress_role_manifests.results }}"

- name: Ingress | Deploy chart
  helm_chart:
    name: "{{ helm_ingress_chart_name }}"
    namespace: "{{ ingress_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_ingress_image_name }}"
    chart_version: "{{ helm_ingress_chart_version }}"
    path_to_values: "{{ role_dir }}/ingress-values.yml"
