---
- name: Rook Ceph | Templates list
  set_fact:
    rook_ceph_role_templates:
      - { file: rook-ceph-namespace.yml }
      - { file: rook-ceph-block-sc.yml }
      - { file: rook-ceph-dashboard-ingress.yml }
      - { file: rook-ceph-block-pool.yml }
      - { file: rook-ceph-fs-pool.yml }
      - { file: rook-ceph-fs-sc.yml }
      - { file: rook-ceph-cephobjectstore.yml }
      - { file: rook-ceph-cluster.yml }
      - { file: rook-ceph-object-user.yml }
      - { file: rook-ceph-prometheus-servicemonitor.yml }
      - { file: rook-ceph-prometheusrule.yml }
      - { file: rook-crd-clusterrole.yml }
      - { file: rook-ceph-certificate.yml }

- name: Rook Ceph | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Rook Ceph | Template values
  template:
    src: "rook-ceph-values.yml"
    dest: "{{ role_dir }}/rook-ceph-values.yml"


- name: Rook Ceph | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ rook_ceph_role_templates }}"
  register: rook_ceph_role_manifests

# Namespace must be deployed before secret.
- name: Rook Ceph | Apply namespace
  kube:
    name: namespace
    namespace: "{{ ceph_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: ns
    filename: "{{ role_dir }}/rook-ceph-namespace.yml"
    state: latest

- name: Rook Ceph | Deploy chart
  helm_chart:
    name: "{{ helm_rook_ceph_chart_name }}"
    namespace: "{{ ceph_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_rook_ceph_image_name }}"
    chart_version: "{{ helm_rook_ceph_chart_version }}"
    atomic: yes   # is atomic so that manifests aren't deployed before CRDs exist
    path_to_values: "{{ role_dir }}/rook-ceph-values.yml"


- name: Rook Ceph | Apply manifests
  kube:
    namespace: "{{ ceph_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ rook_ceph_role_manifests.results }}"