---
- name: Rook Ceph | Master tasks
  when:
    - inventory_hostname == groups['kube-master'][0]
  block:
  - name: Rook Ceph | Templates list
    set_fact:
      rook_ceph_role_templates:
        - { file: rook-ceph-namespace.yml }
        - { file: rook-ceph-block-sc.yml}
        - { file: rook-ceph-cephblockpool.yml }
        - { file: rook-ceph-cephobjectstore.yml }
        - { file: rook-ceph-cluster.yml }
        - { file: rook-ceph-dashboard-ingress.yml }
        - { file: rook-ceph-object-user.yml }
        - { file: rook-ceph-prometheus-servicemonitor.yml }
        - { file: rook-ceph-prometheusrule.yml }
        - { file: rook-crd-clusterrole.yml }

  - name: Rook Ceph | Create subfolder
    file:
      path: "{{ role_dir }}"
      state: directory
      mode: '0755'

  - name: Rook Ceph | Create manifests
    template:
      src: "{{ item.file }}"
      dest: "{{ role_dir }}/{{ item.file }}"
    with_items: "{{ rook_ceph_role_templates }}"
    register: rook_ceph_role_manifests

  #---- remove block and file artifacts
  # reference: https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md
  - name: Rook Ceph | Ignore errors
    ignore_errors: yes
    block: 
    - name: Rook Ceph | Remove replicapool
      shell: "{{ bin_dir }}/kubectl delete cephblockpool replicapool -n {{ ceph_namespace }}"

    - name: Rook Ceph | Remove storage class
      shell: "{{ bin_dir }}/kubectl delete storageclass rook-ceph-block -n {{ ceph_namespace }}"

    - name: Rook Ceph | Patch cephcluster finalizer
      shell: "{{ bin_dir }}/kubectl patch cephcluster rook-ceph --type merge -p '{\"metadata\":{\"finalizers\": [null]}}' -n {{ ceph_namespace }}"

    - name: Rook Ceph | Remove cephcluster
      shell: "{{ bin_dir }}/kubectl delete cephcluster rook-ceph -n {{ ceph_namespace }}"

  #---- Deploy chart and templates
  - name: Rook Ceph | Remove chart
    helm_chart:
      name: "{{ helm_rook_ceph_chart_name }}"
      namespace: "{{ ceph_namespace }}"
      bin_dir: "{{ bin_dir }}"
      chart_src: "{{ grayskull_dir }}/{{ helm_rook_ceph_image_name }}"
      chart_version: "{{ helm_rook_ceph_chart_version }}"
      state: absent

  - name: Rook Ceph | Remove manifest products
    kube:
      namespace: "{{ ceph_namespace }}"
      kubectl: "{{ bin_dir }}/kubectl"
      filename: "{{ role_dir }}/{{ item.item.file }}"
      state: absent
    with_items: "{{ rook_ceph_role_manifests.results }}"

  #---- Create secret
  - name: Rook Ceph | Check for secret
    shell: "{{ bin_dir }}/kubectl get secrets -n {{ ceph_namespace }}"
    register: rook_ceph_secret_exists
    changed_when: false

  - name: Rook Ceph | Remove secret
    shell: "{{ bin_dir }}/kubectl delete secret {{ ingress_secretName }} -n {{ ceph_namespace }}"
    when: 
      - "ingress_secretName in rook_ceph_secret_exists.stdout"


  #---- Delete namespace and role folder

  - name: Rook Ceph | Delete namespace
    kube:
      namespace: "{{ ceph_namespace }}"
      kubectl: "{{ bin_dir }}/kubectl"
      filename: "{{ role_dir }}/rook-ceph-namespace.yml"
      state: absent

  - name: Rook Ceph | Delete subfolder
    file:
      path: "{{ role_dir }}"
      state: absent


#---- Remove all ceph stuff from hosts
- name: Rook Ceph | Ignore errors
  ignore_errors: true
  block:
  - name: Rook Ceph | Remove rook directory
    shell: "rm -rf /var/lib/rook"

  - name: Rook Ceph | Zap disk
    shell: "sgdisk --zap-all /dev/nvme1n1"

  - name: Rook Ceph | Remove device
    shell: "ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove %"

  - name: Rook Ceph | Remove Ceph
    shell: "rm -rf /dev/ceph-*"

  - name: Rook Ceph | Remove Ceph device from mapper
    shell: "rm -rf /dev/mapper/ceph-*"


  
