ceph:
  mon:
    count: 5
  ingress:
    enabled: true
    path: /
    hosts:
      - ceph.gsp.test
    tls:
      - hosts:
          - ceph.gsp.test
        secretName: ceph-gsp-tls
  defaultStorage:
    enabled: true