proxy:
  oidc:
    discoveryURL: "https://auth.{{ grayskull_domain }}/auth/realms/master"
    clientID: kubernetes
    clientSecret: 
    redirectURL: "http://admin.{{ grayskull_domain }}"
  extraArgs:
    - --skip-openid-provider-tls-verify
    - --secure-cookie=false

ingress:
  enabled: true
  hosts: 
    - "admin.{{ grayskull_domain }}"
  tls:
    - hosts:
        - "admin.{{ grayskull_domain }}"
      secretName: dashboard-gsp-tls
