elasticsearch:
  host: elasticsearch-master
  port: 9200

inputs:
  main: |-
    input {
      tcp {
        port => 1514
        codec => json_lines
      }
      beats {
        port => 5044
      }
    }

outputs:
  main: |-
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
        index => "%{[app_name]}-%{+YYYY.MM.dd}"
      }
    }
