elasticsearch:
  host: elasticsearch-master
  port: 9200

inputs:
  main: |-
    input {
      tcp {
        port => 1514
        codec => json_lines
      }
      beats {
        port => 5044
      }
    }

filters:
  main: |-
    filter {
      if [app_name] {
        mutate { add_field => { "[@metadata][index]" => "%{[app_name]}" } }
      } else {
        mutate { add_field => { "[@metadata][index]" => "logstash" } }
      }
    }

outputs:
  main: |-
    output {
      stdout { codec => rubydebug { metadata => true } }

      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
        index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
      }
    }
