{% if routing is defined and routing == "path" -%}

grafana:
  grafana.ini:
    server:
      root_url: "https://{{ grayskull_domain }}/graph"
      serve_from_sub_path: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    path: /graph/?(.*)
    hosts:
      - "{{ grayskull_domain }}"
    tls:
      - hosts:
          - "{{ grayskull_domain }}"
        secretName: prom-gsp-tls

{% else %}

grafana:
  ingress:
    enabled: true
    paths: [/]
    hosts:
      - "graph.{{ grayskull_domain }}"
    tls:
      - hosts:
          - "graph.{{ grayskull_domain }}"
        secretName: prom-gsp-tls

{% endif -%}

kubeApiServer:
  enabled: true