#!/usr/bin/env python3

import subprocess
import json
import pprint
from jinja2 import FileSystemLoader, Environment

templateLoader = FileSystemLoader(searchpath="./")
templateEnv = Environment(loader=templateLoader)
TEMPLATE_FILE = "inv_rke_gray.yml.tpl"
template = templateEnv.get_template(TEMPLATE_FILE)

getJsonCmd = "terraform state pull"
jsonData,_ = subprocess.Popen([getJsonCmd], shell=True, stdout=subprocess.PIPE).communicate()

data = json.loads(jsonData)['resources']

environments = {}
resources = list(filter(lambda x: x['type'] == "aws_instance", data))
for resource in resources:
        k8s_type = resource['name']
        for instance in resource['instances']:
            attr = instance['attributes']
            environment = attr['tags']['Environment']
            real_type = ""
            if k8s_type == "k8s_worker":
                real_type = "worker"
            if k8s_type == "k8s_master":
                real_type = "master"
            if k8s_type == "k8s_rancher":
                real_type = "rancher"
            data = {
                "public_ip": attr['public_ip'],
                "public_dns": attr['public_dns'],
                "private_ip": attr['private_ip'],
                "private_dns": attr['private_dns'],
                "name": attr['tags']['Name'],
                "type": real_type,
                "env": environment

            }
            if not environments.get(environment):
                environments[environment] = []
            environments[environment].append(data)

for e in environments.keys():
    print("#Environment:", e)
    print(template.render(instances=environments[e]))

