#!/usr/bin/env python3

import subprocess
import json
import pprint
from jinja2 import FileSystemLoader, Environment

templateLoader = FileSystemLoader(searchpath="./")
templateEnv = Environment(loader=templateLoader)
TEMPLATE_FILE = "inventory.ini.tpl"
template = templateEnv.get_template(TEMPLATE_FILE)

getJsonCmd = "terraform state pull"
jsonData,__ = subprocess.Popen([getJsonCmd], shell=True, stdout=subprocess.PIPE).communicate()
data = json.loads(jsonData)['resources']

environment,__ = subprocess.Popen(["terraform workspace show"], shell=True, stdout=subprocess.PIPE).communicate()
environment = environment.decode("utf-8").strip() # decode /n then strip all whitespace

hosts = []
resources = list(filter(lambda x: x['type'] == "aws_instance", data))
for resource in resources:
        k8s_type = resource['name']
        for instance in resource['instances']:
            attr = instance['attributes']
            real_type = ""
            if k8s_type == "k8s_worker":
                real_type = "worker"
            if k8s_type == "k8s_master":
                real_type = "master"
            data = {
                "public_ip": attr['public_ip'],
                "public_dns": attr['public_dns'],
                "private_ip": attr['private_ip'],
                "private_dns": attr['private_dns'],
                "name": attr['tags']['Name'],
                "type": real_type,
            }
            hosts.append(data)

print(template.render(instances=hosts, env=environment))

