---
auth_namespace: grayskull-auth
subfolder: auth-role
role_dir: "{{ grayskull_dir }}/{{ subfolder }}"
auth_secrets_dir: "{{ role_dir }}/secrets"

auth_passwd_secretName: "auth-gsp-passwd"
auth_passwd_file: "{{ auth_secrets_dir }}/password"

ingress_secretName: "auth-gsp-tls"
ingress_tls_cert: "{{ auth_secrets_dir }}/tls.crt"
ingress_tls_key: "{{ auth_secrets_dir }}/tls.key"

kube_ca_path: "/etc/kubernetes/ssl"

task_mode: "install"

helm_keycloak_name: "{{ platform_prefix }}-keycloak"