version: '{{compose_syntax_version}}'

networks:
  {{security_network}}:
     external: true
  {{proxy_network}}:
     external: true
  db:

volumes:
  mysql_data:

services:
  keycloak:
    image: {{docker_registry}}/{{keycloak_image}}:{{keycloak_version}}
    networks:
      - default
      - {{proxy_network}}
      - {{security_network}}
      - db
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network={{proxy_network}}"
        - "traefik.frontend.rule=Host:{{hostname}};PathPrefix:{{keycloak_path}}"
        - "traefik.enable=true"
    environment:
      KEYCLOAK_HOSTNAME: {{hostname}}{{keycloak_path}}
      #KEYCLOAK_HTTP_PORT: 80
      #KEYCLOAK_HTTPS_PORT: 443
      KEYCLOAK_USER: {{keycloak_user}}
      KEYCLOAK_PASSWORD: {{keycloak_pass}}
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: {{mysql_user}}
      DB_PASSWORD: {{mysql_pass}}

  mysql:
    image: {{docker_registry}}/{{mysql_image}}:{{mysql_version}}
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: {{mysql_user}}
      MYSQL_PASSWORD: {{mysql_pass}}
    volumes:
      - mysql_data:/var/lib/mysql