task_modes:
  - download
  - install

ceph_namespace: "grayskull-storage"
# Options are block, fs, none
ceph_defaultStorage: block
ceph_mon_count: "{{ groups['kube-storage'] | length }}"
ceph_objectstore_name: gsp-store
ceph_data_dir: /storage/rook #/var/lib/rook

gitops_namespace_dir: "{{ gitops_repo_dir }}/namespaces/{{ ceph_namespace }}"
gitops_release_dir: "{{ gitops_repo_dir }}/releases/{{ ceph_namespace }}"
gitops_workload_dir: "{{ gitops_repo_dir }}/workloads/{{ ceph_namespace }}"
# Hacky solution to getting values file into HelmRelease
# Read the values file, template, and indent it. Then assign it to a variable
# When we template the helm release file the contents of this variable will be loaded
values: "{{ lookup('template', 'templates/rook-ceph-values.yml') | indent( width=4, first=True ) }}"

prometheusOperator_enabled: true

subfolder: "rook-ceph-role"
role_dir: "{{ grayskull_dir }}/{{ subfolder }}"

grayskull_ca_issuer_name: grayskull-ca-issuer

helm_rook_ceph_chart_name: "{{ platform_prefix }}-rook-ceph"
helm_rook_ceph_repo_url: https://charts.rook.io/release
helm_rook_ceph_image_name: rook-ceph
helm_rook_ceph_chart_version: v1.1.0

template_ceph_image: ceph/ceph
template_ceph_image_version: v14.2.4-20191112

ingress_url: "ceph.{{ grayskull_domain }}"
ingress_secretName: "ceph-gsp-tls" #TODO: make this into admin-gsp-tls
ingress_path: "/"