task_modes:
  - download
  - install

elk_namespace: grayskull-logs

subfolder: elk-role
role_dir: "{{ grayskull_dir }}/{{ subfolder }}"

grayskull_ca_issuer_name: grayskull-ca-issuer
helm_elasticsearch_chart_name: "{{ platform_prefix }}-elasticsearch"
helm_elasticsearch_repo_url: https://helm.elastic.co
helm_elasticsearch_image_name: elasticsearch
helm_elasticsearch_chart_version: 7.5.2
helm_kibana_chart_name: "{{ platform_prefix }}-kibana"
helm_kibana_repo_url: https://helm.elastic.co
helm_kibana_image_name: kibana
helm_kibana_chart_version: 7.5.2
helm_logstash_chart_name: "{{ platform_prefix }}-logstash"
helm_logstash_repo_url: https://helm.elastic.co
helm_logstash_image_name: logstash
helm_logstash_chart_version: 7.5.2
helm_metricbeat_chart_name: "{{ platform_prefix }}-metricbeat"
helm_metricbeat_repo_url: https://helm.elastic.co
helm_metricbeat_image_name: metricbeat
helm_metricbeat_chart_version: 7.5.2

ingress_secretName: "elk-gsp-tls"
