version: @composeSyntaxVersion@

services:
  portainer:
    image: ${DOCKER_REGISTRY:-docker.io}/@portainerImage@
    networks:
      - @publicNetwork@
      - default
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=9000"
        - "traefik.docker.network=@publicNetwork@"
        - "traefik.frontend.rule=Host:${MANAGEMENT_HOSTNAME:-swarm}.${DOMAIN:-test}"
        - "traefik.enable=true"
    volumes:
      - type: volume
        source: portainer_data
        target: /data

  agent:
    image: ${DOCKER_REGISTRY:-docker.io}/@portainerAgentImage@
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes
      - type: bind
        source: /
        target: /host
    networks:
      - default
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  portainer_data:

networks:
  default:
  @publicNetwork@:
    external: true
