apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: registry-cert
spec:
  secretName: {{ ingress_secretName }}
  issuerRef:
    name: {{ grayskull_ca_issuer_name }}
    kind: ClusterIssuer
  dnsNames:
    - registry.{{ grayskull_domain }}
