version: "3.4"

services:
    vault-stk:
        image: vault
        ports: 
          - published: 8200
            target: 8200
            mode: "host"
        volumes:
          - ./vault_files:/vault
        #Needed to run in production mode
        command:
          - "server"

        environment:
            VAULT_ADDR: http://0.0.0.0:8200
            VAULT_API_ADDR: http://0.0.0.0:8200
            SKIP_SETCAP: 1
    
    spring-svr-stk:
        image: spring-svr
        ports: 
          - published: 8888
            target: 8888
            mode: "host"

    spring-client-stk:
        image: spring-client
        ports: 
          - published: 8080
            target: 8080
            mode: "host"


