defaultEntryPoints = ["http","https"]
    logLevel = "DEBUG"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
