task_modes:
  - download
  - install

ingress_namespace: grayskull-ingress
subfolder: ingress-role
role_dir: "{{ grayskull_dir }}/{{ subfolder }}"

gitops_namespace_dir: "{{ gitops_repo_dir }}/namespaces/{{ ingress_namespace }}"
gitops_release_dir: "{{ gitops_repo_dir }}/releases/{{ ingress_namespace }}"
gitops_workload_dir: "{{ gitops_repo_dir }}/workloads/{{ ingress_namespace }}"
# Hacky solution to getting values file into HelmRelease
# Read the values file, template, and indent it. Then assign it to a variable
# When we template the helm release file the contents of this variable will be loaded
values: "{{ lookup('template', 'templates/ingress-values.yml') | indent( width=4, first=True ) }}"

helm_ingress_chart_name: "{{ platform_prefix }}-ingress"
helm_ingress_repo_url: "https://kubernetes-charts.storage.googleapis.com" #stable
helm_ingress_image_name: nginx-ingress
helm_ingress_chart_version: 1.24.4
