- name: Certificates | Check if CA exists
  stat:
    path: "{{ ca_path }}.pem"
  register: ca

- name: Certificates | Create a self-signed CA
  block:
    - name: Certificates | Check for cfssl
      stat:
        path: "{{ bin_dir }}/cfssl"
      register: cfssl

    - name: Certificates | Check for cfssljson
      stat:
        path: "{{ bin_dir }}/cfssljson"
      register: cfssljson

    - name: Certificates | Install cfssl and cfssljson
      block:
        - name: Certificates | Download cfssl binary
          get_url:
            url: "{{ cfssl_download_path }}"
            dest: "{{ bin_dir }}/cfssl"
            mode: '0755'

        - name: Certificates | Download cfssljson binary
          get_url:
            url: "{{ cfssljson_download_path }}"
            dest: "{{ bin_dir }}/cfssljson"
            mode: '0755'
      when: not cfssl.stat.exists or not cfssljson.stat.exists

    - name: Certificates | Create a self-signed CA
      shell: "{{ bin_dir }}/cfssl gencert -initca {{ ca_csrjson_src }} | {{ bin_dir }}/cfssljson -bare {{ ca_path }}"
  when: not ca.stat.exists