- name: Dash-proxy | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Dash-proxy | Download chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_dash_proxy_repo_url }} \
    --version {{ helm_dash_proxy_chart_version }} \
    --destination {{ role_dir }} \
    --untar \
    {{ helm_dash_proxy_image_name }}"  