#---- Templates values
- name: Setup | Create subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: directory
    mode: '0755'

- name: Ingress | Template values file
  template:
    src: "dash-proxy-values.yml"
    dest: "{{ dash_proxy_file_location }}"

#---- Amend customizations with UUID secret
- name: Dash-proxy | Stat secrets directory
  stat:
    path: "{{ dash_proxy_file_location }}"
  register: stat_result

- name: Dash-proxy | Check for file or fail
  fail:
    msg: "{{ dash_proxy_file_location }} does not exist, can't add UUID so can't deploy dash-proxy. Ensure the file got copied"
  when: stat_result is defined and not stat_result.stat.exists

- name: Dash-proxy | Amend customization file with UUID
  lineinfile:
    path: "{{ dash_proxy_file_location }}"
    regexp: '.*clientSecret: '
    line: "    clientSecret: {{ client_UUID }}"

- name: Dash-proxy | Deploy chart
  helm_chart:
    name: "{{ helm_dash_proxy_chart_name }}"
    namespace: "{{ dash_proxy_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_dash_proxy_image_name }}"
    chart_version: "{{ helm_dash_proxy_chart_version }}"
    path_to_values: "{{ dash_proxy_file_location }}"

#TODO: see about adding the cert so keycloak proxy can use it, and removing insecure params from customization file.
