#---- Remove chart
- name: Dash-proxy | Remove chart
  helm_chart:
    name: "{{ helm_dash_proxy_chart_name }}"
    namespace: "{{ dash_proxy_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_dash_proxy_image_name }}"
    chart_version: "{{ helm_dash_proxy_chart_version }}"
    state: absent
