---
- hosts: kube-setup-delegate
  become: yes
  tasks:

    - name: Credentials | Get Correct CA Certificate
      command:
        argv:
          - openssl
          - x509
          - -in
          - /etc/kubernetes/ssl/ca.crt
      register: kube_api_ca_crt

    - name: Credentials | Save cert content
      set_fact:
        kube_ca: "{{ kube_api_ca_crt.stdout | b64encode | string }}"

    - name: Credentials | Get kubeconfig
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/grayskull/admin.conf
        flat: yes

- hosts: localhost
  tasks:
      
    - name: Credentials | Get original host
      set_fact:
        original_host: "{{ groups['kube-setup-delegate'][0] }}"

    - name: Credentials | Replace invalid ca cert in kubeconfig
      lineinfile:
        path: /tmp/grayskull/admin.conf
        regexp: '.*certificate-authority-data: '
        line: "    certificate-authority-data: {{ hostvars[original_host]['kube_ca'] }}"

    - name: Credentials | Replace kube master ip
      lineinfile:
        path: /tmp/grayskull/admin.conf
        regexp: '.*server: '
        line: "    server: https://{{ hostvars[original_host]['public_ip'] }}:6443"

    - debug:
        msg:
          - "New kubeconfig available at /tmp/grayskull/admin.conf"
