---
- hosts: kube-master
  become: yes
  tasks:

    # ---- Helm and Kubectl set up
    - name: Setup | Export KUBECONFIG env var
      lineinfile:
        path: /etc/profile
        line: export KUBECONFIG=/etc/kubernetes/admin.conf
        create: yes

    - name: Setup | Create grayskull directory
      file:
        path: "{{ grayskull_dir }}"
        state: directory
        mode: '0755'

    - name: Setup | Copy over Tiller RBAC
      copy:
        src: tiller-rbac.yml
        dest: "{{ grayskull_dir }}/tiller-rbac.yml"

    - name: Setup | Apply Tiller RBAC definition
      kube:
        name: tiller-rbac
        namespace: kube-system
        kubectl: "{{ bin_dir }}/kubectl"
        filename: "{{ grayskull_dir }}/tiller-rbac.yml"
        state: present

    - name: Setup | Retrieve helm binary archive
      unarchive:
        src: https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
        dest: /tmp
        creates: "{{ bin_dir }}/helm"
        remote_src: yes

    - name: Setup | Move helm binary into place
      command: >
        cp /tmp/linux-amd64/helm {{ bin_dir }}
        creates={{ bin_dir }}/helm

    - name: Setup | Set up Helm and Tiller
      command: "{{ bin_dir }}/helm init --service-account tiller"
      register: helm_init_result
      changed_when: "'already installed' not in helm_init_result.stdout"


    # ---- Make Certificates
    - include: certificate-tasks.yml


    # ---- Copy Customizations to remote
    - name: Customization Files | Create list
      set_fact:
        customizations_files:
          - { file: customizations/ceph.yml }
          - { file: customizations/keycloak.yml }
          - { file: customizations/nginx-ingress.yml }
          - { file: customizations/prometheus.yml }
          - { file: customizations/elk.yml }

    - name: Customization Files | Create customizations directory
      file:
        path: "{{ grayskull_dir }}/customizations"
        state: directory
        mode: '0755'

    - name: Customization Files | Move to kube-master
      copy:
        src: "{{ item.file }}"
        dest: "{{ grayskull_dir }}/{{ item.file }}"
      with_items: "{{ customizations_files }}"

    # ---- Deploy Ingress
    - name: Nginx-Ingress | Check for grayskull-ingress namespace
      shell: "{{ bin_dir }}/kubectl get namespaces"
      register: ingress_ns_exists
      changed_when: false

    - name: Nginx-Ingress | Create grayskull-ingress namespace
      shell: "{{ bin_dir }}/kubectl create namespace grayskull-ingress"
      when: "'grayskull-ingress' not in ingress_ns_exists.stdout"

    - name: Nginx-Ingress | Deploy chart
      kube_chart:
        namespace: "grayskull-ingress"
        chart_dest: "{{ grayskull_dir }}"
        bin_dir: "{{ bin_dir }}"
        chart_src: stable/nginx-ingress
        chart_version: 1.6.16
        path_to_values: "{{ grayskull_dir }}/customizations/nginx-ingress.yml"


- hosts: kube-master
  become: yes
  roles:
    - prometheus_role   # must be deployed before rook-ceph
    - rook_ceph_role
    - keycloak_role 
    - dashboard_role
    - elk_role
