
---
- name: Setup | Stat for key file
  stat:
    path: "{{ grayskull_dir }}/secrets/harbor_key"
  register: stat_result

- name: Setup | Check for key file or create
  when: stat_result is defined and not stat_result.stat.exists
  block: 
  - name: Setup | Generate key
    set_fact: 
      harbor_key: "{{ (99999999 | random | to_uuid)[0:16] }}"
      cacheable: no

  - name: Setup | Write key to file
    copy: 
      content: "{{ harbor_key }}"
      dest: "{{ grayskull_dir }}/secrets/harbor_key"

- name: Setup | Get key file contents 
  when: stat_result is defined and stat_result.stat.exists
  block:
  - name: Setup | Slurp file
    slurp: 
      src: "{{ grayskull_dir }}/secrets/harbor_key"
    register: slurp_contents

  - name: Setup | Reuse key
    set_fact:
      harbor_key: "{{ slurp_contents.content | b64decode }}"