- name: Cert-manager | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Cert-manager | Download custom resource definitions
  get_url:
    url: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
    dest: "{{ role_dir }}/crds.yml"

- name: Cert-manager | Download chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_cert_manager_repo_url }} \
    --version {{ helm_cert_manager_chart_version }} \
    --destination {{ role_dir }} \
    --untar \
    {{ helm_cert_manager_image_name }}"
