- name: Cert-manager | List cluster issuer manifests
  set_fact:
    cluster_issuer_templates:
      - { file: cert-manager-grayskull-issuer.yml }
      - { file: cert-manager-kube-issuer.yml }

- name: Cert-manager | Template cluster issuer manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ cluster_issuer_templates }}"
  register: cluster_issuer_manifests

- name: Cert-manager | Remove cluster issuer manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: absent
  with_items: "{{ cluster_issuer_manifests.results }}"

- name: Cert-manager | Remove cluster issuer secrets
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    name: "{{ item }}"
    namespace: "{{ cert_manager_namespace }}"
    resource: secret
    state: absent
  loop:
    - "{{ grayskull_ca_issuer_secret }}"
    - "{{ kube_ca_issuer_secret }}"

- name: Cert-manager | Remove chart
  helm_chart:
    name: "{{ helm_cert_manager_chart_name }}"
    namespace: "{{ cert_manager_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_cert_manager_image_name }}"
    chart_version: "{{ helm_cert_manager_chart_version }}"
    state: absent

- name: Cert-manager | Remove custom resource definitions
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/crds.yml"
    state: absent

- name: Cert-manager | Template namespace manifest
  template:
    src: cert-manager-namespace.yml
    dest: "{{ role_dir }}/cert-manager-namespace.yml"

- name: Cert-manager | Delete namespace manifest
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/cert-manager-namespace.yml"
    state: absent
