version: '3.7'

volumes:
  mysql_data:

networks:
  proxy:
    external: true
  security:
    external: true
  db:

services:
  proxy:
    image: ${DOCKER_REGISTRY:-docker.io}/traefik:1.7
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5G'
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    command: 
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=${DOMAIN}"
      - "--docker.watch"
      - "--insecureSkipVerify=true"

  resource:
    image: ${DOCKER_REGISTRY:-docker.io}/resource-server
    networks:
      - security

  gateway:
    image: ${DOCKER_REGISTRY:-docker.io}/spring-gateway
    networks:
      - security
      - proxy
    deploy:
      labels:
        - "traefik.frontend.rule=Host:gateway.${DOMAIN:-docker.localhost}"
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.passHostHeader=true"
    environment:
      KC_BASE-URL: http://keycloak.${DOMAIN:-docker.localhost}
  keycloak:
    image: ${DOCKER_REGISTRY:-docker.io}/jboss/keycloak:4.8.3.Final
    networks:
      - default
      - proxy
      - security
      - db
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:keycloak.${DOMAIN:-docker.localhost}"
        - "traefik.enable=true"
    environment:
      KEYCLOAK_HOSTNAME: keycloak.${DOMAIN:-docker.localhost}
      #      KEYCLOAK_HTTP_PORT: 80
      #KEYCLOAK_HTTPS_PORT: 443
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - mysql

  mysql:
    image: ${DOCKER_REGISTRY:-docker.io}/mysql:5
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
