networks:
  proxy:
    external: true
  security:
    external: true
services:
  gateway:
    image: spring-gateway
    labels:
      traefik.docker.network: proxy
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: Host:gateway.docker.localhost
      traefik.port: '8080'
    networks:
      default: null
      proxy: null
      security: null
  keycloak:
    depends_on:
    - mysql
    environment:
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_USER: keycloak
      DB_VENDOR: MYSQL
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
    image: jboss/keycloak:4.8.3.Final
    labels:
      traefik.docker.network: proxy
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: Host:keycloak
      traefik.port: '8080'
    networks:
      default: null
      proxy: null
      security: null
    ports:
    - published: 8080
      target: 8080
  mysql:
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
    image: mysql:5
    volumes:
    - mysql_data:/var/lib/mysql:rw
  resource:
    image: resource-server
    networks:
      default: null
      security: null
  reverse-proxy:
    command: --api --docker
    image: traefik
    networks:
      default: null
      proxy: null
    ports:
    - published: 80
      target: 80
    - published: 8081
      target: 8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.3'
volumes:
  mysql_data:
    driver: local

