apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prom-cert
  namespace: "{{ prometheus_namespace }}"
spec:
  secretName: {{ ingress_secretName }}
  issuerRef:
    name: {{ grayskull_ca_issuer_name }}
    kind: ClusterIssuer
  dnsNames:
    - prom.{{ grayskull_domain }}
    - graph.{{ grayskull_domain }}
    - alert.{{ grayskull_domain }}
