prometheus:
  ingress:
    enabled: true
    paths: [/]
    hosts:
      - "prom.{{ grayskull_domain }}"
    tls:
      - hosts:
          - "prom.{{ grayskull_domain }}"
        secretName: prom-gsp-tls

grafana:
  ingress:
    enabled: true
    paths: [/]
    hosts:
      - "graph.{{ grayskull_domain }}"
    tls:
      - hosts:
          - "graph.{{ grayskull_domain }}"
        secretName: prom-gsp-tls

alertmanager:
  ingress:
    enabled: true
    paths: [/]
    hosts:
      - "alert.{{ grayskull_domain }}"
    tls:
      - hosts:
          - "alert.{{ grayskull_domain }}"
        secretName: prom-gsp-tls

kubeApiServer:
  enabled: true