---
- name: ELK | Download Elasticsearch chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_elasticsearch_repo_url }} \
    --version {{ helm_elasticsearch_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_elasticsearch_image_name }}"

- name: ELK | Download Kibana chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_kibana_repo_url }} \
    --version {{ helm_kibana_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_kibana_image_name }}"

- name: ELK | Download Logstash chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_logstash_repo_url }} \
    --version {{ helm_logstash_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_logstash_image_name }}"

- name: ELK | Download Metricbeat chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_metricbeat_repo_url }} \
    --version {{ helm_metricbeat_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_metricbeat_image_name }}"
