---
- name: ELK | Download Elasticsearch chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_elasticsearch_repo_url }} \
    --version {{ helm_elasticsearch_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_elasticsearch_image_name }}"

- name: ELK | Download Kibana chart
  shell: "{{ bin_dir }}/helm fetch \
    --repo {{ helm_kibana_repo_url }} \
    --version {{ helm_kibana_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_kibana_image_name }}"

- name: ELK | Download Logstash chart
  shell: "{{ bin_dir }}/helm fetch \
    --version {{ helm_logstash_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_logstash_chart_type }}/{{ helm_logstash_image_name }}"

- name: ELK | Download Fluentd chart
  shell: "{{ bin_dir }}/helm fetch \
    --version {{ helm_fluentd_chart_version }} \
    --destination {{ grayskull_dir }} \
    --untar \
    {{ helm_fluentd_chart_type }}/{{ helm_fluentd_image_name }}"