- name: ELK | Create namespace folder
  file:
    path: "{{ gitops_namespace_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Create releases folder
  file:
    path: "{{ gitops_release_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Create workloads folder
  file:
    path: "{{ gitops_workload_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Template namespace
  template:
    src: elk-namespace.yml
    dest: "{{ gitops_namespace_dir }}/elk-namespace.yml"

#---- Need to get the values into the release but don't want to duplicate them in case values file changes.

- name: ELK | Release list
  set_fact:
    elk_values_templates:
      - { file: elasticsearch-release.yml }
      - { file: kibana-release.yml }
      - { file: logstash-release.yml }

- name: ELK | Template releases
  template:
    src: "gitops/{{ item.file }}"
    dest: "{{ gitops_release_dir }}/{{ item.file }}"
  with_items: "{{ elk_values_templates }}"

- name: ELK | Template certificate
  template:
    src: elk-certificate.yml
    dest: "{{ gitops_workload_dir }}/elk-certificate.yml"