- name: ELK | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Roles list
  set_fact:
    elk_values_templates:
      - { file: elasticsearch-values.yml }
      - { file: kibana-values.yml }
      - { file: logstash-values.yml }
      # - { file: metricbeat-values.yml }

- name: ELK | Template Values
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ elk_values_templates }}"
  register: elk_values_manifests

- name: ELK | Templates list
  set_fact:
    elk_role_templates:
      - { file: elk-namespace.yml }
      - { file: elk-certificate.yml }

- name: ELK | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ elk_role_templates }}"
  register: elk_role_manifests

# Namespace must be deployed before secret.
- name: ELK | Apply manifests
  kube:
    namespace: "{{ elk_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ elk_role_manifests.results }}"

- name: ELK | Deploy Elasticsearch chart
  helm_chart:
    name: "{{ helm_elasticsearch_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_elasticsearch_image_name }}"
    chart_version: "{{ helm_elasticsearch_chart_version }}"
    path_to_values: "{{ role_dir }}/elasticsearch-values.yml"

- name: ELK | Deploy Kibana chart
  helm_chart:
    name: "{{ helm_kibana_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_kibana_image_name }}"
    chart_version: "{{ helm_kibana_chart_version }}"
    path_to_values: "{{ role_dir }}/kibana-values.yml"

- name: ELK | Deploy Logstash chart
  helm_chart:
    name: "{{ helm_logstash_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_logstash_image_name }}"
    chart_version: "{{ helm_logstash_chart_version }}"
    path_to_values: "{{ role_dir }}/logstash-values.yml"

# - name: ELK | Deploy Metricbeat chart
#   helm_chart:
#     name: "{{ helm_metricbeat_chart_name }}"
#     namespace: "{{ elk_namespace }}"
#     bin_dir: "{{ bin_dir }}"
#     chart_src: "{{ role_dir }}/{{ helm_metricbeat_image_name }}"
#     chart_version: "{{ helm_metricbeat_chart_version }}"
#     path_to_values: "{{ role_dir }}/metricbeat-values.yml"
