- name: ELK | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Roles list
  set_fact:
    elk_values_templates:
      - { file: elasticsearch-values.yml }
      - { file: fluentd-values.yml }
      - { file: kibana-values.yml }
      - { file: logstash-values.yml }

- name: ELK | Template Values
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ elk_values_templates }}"
  register: elk_role_manifests

- name: ELK | Templates list
  set_fact:
    elk_role_templates:
      - { name: namespace, file: elk-namespace.yml, type: ns }

- name: ELK | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ elk_role_templates }}"
  register: elk_role_manifests

# Namespace must be deployed before secret.
- name: ELK | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ elk_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ elk_role_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]


#---- Create secret
- name: ELK | Check for secret
  shell: "{{ bin_dir }}/kubectl get secrets -n {{ elk_namespace }}"
  register: elk_secret_exists
  changed_when: false

- name: ELK | Create secret
  shell: "{{ bin_dir }}/kubectl create secret generic {{ ingress_secretName }} --from-file {{ ingress_tls_cert }} --from-file {{ ingress_tls_key }} -n {{ elk_namespace }}"
  when: "ingress_secretName not in elk_secret_exists.stdout"


#---- Deploy chart and templates
- name: ELK | Add repo
  shell: "{{ bin_dir }}/helm repo add elastic https://helm.elastic.co"

- name: ELK | Deploy Elasticsearch chart
  helm_chart:
    name: "{{ helm_elasticsearch_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: elastic/elasticsearch
    chart_version: 7.1.1
    path_to_values: "{{ role_dir }}/elasticsearch-values.yml"

- name: ELK | Deploy Kibana chart
  helm_chart:
    name: "{{ helm_kibana_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: elastic/kibana
    chart_version: 7.1.1
    path_to_values: "{{ role_dir }}/kibana-values.yml"

- name: ELK | Deploy Logstash chart
  helm_chart:
    name: "{{ helm_logstash_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: stable/logstash
    chart_version: 1.13.0
    path_to_values: "{{ role_dir }}/logstash-values.yml"

- name: ELK | Deploy fluentd chart
  helm_chart:
    name: "{{ helm_fluentd_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: stable/fluentd
    chart_version: 1.10.0
    path_to_values: "{{ role_dir }}/fluentd-values.yml"
