#---- Remove the charts
- name: ELK | Create subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: directory
    mode: '0755'

- name: ELK | Remove Elasticsearch chart
  helm_chart:
    name: "{{ helm_elasticsearch_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: elastic/elasticsearch
    chart_version: 7.1.1
    state: absent

- name: ELK | Remove Kibana chart
  helm_chart:
    name: "{{ helm_kibana_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: elastic/kibana
    chart_version: 7.1.1
    state: absent

- name: ELK | Remove Logstash chart
  helm_chart:
    name: "{{ helm_logstash_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: stable/logstash
    chart_version: 1.13.0
    state: absent

- name: ELK | Remove fluentd chart
  helm_chart:
    name: "{{ helm_fluentd_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: stable/fluentd
    chart_version: 1.10.0
    state: absent

#---- Copy over the templates to be used with kubectl delete -f. 
- name: ELK | Templates list
  set_fact:
    elk_role_templates:
      - { name: namespace, file: elk-namespace.yml, type: ns }

- name: ELK | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.file }}"
  with_items: "{{ elk_role_templates }}"
  register: elk_role_manifests

- name: ELK | Remove manifest products
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ elk_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.item.file }}"
    state: "absent"
  with_items: "{{ elk_role_manifests.results }}"

- name: ELK | Delete subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: absent