#---- Remove the charts
- name: ELK | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: ELK | Remove Elasticsearch chart
  helm_chart:
    name: "{{ helm_elasticsearch_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_elasticsearch_image_name }}"
    chart_version: "{{ helm_elasticsearch_chart_version }}"
    state: absent

- name: ELK | Remove Kibana chart
  helm_chart:
    name: "{{ helm_kibana_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_kibana_image_name }}"
    chart_version: "{{ helm_kibana_chart_version }}"
    state: absent

- name: ELK | Remove Logstash chart
  helm_chart:
    name: "{{ helm_logstash_chart_name }}"
    namespace: "{{ elk_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_logstash_image_name }}"
    chart_version: "{{ helm_logstash_chart_version }}"
    state: absent

# - name: ELK | Remove Metricbeat chart
#   helm_chart:
#     name: "{{ helm_metricbeat_chart_name }}"
#     namespace: "{{ elk_namespace }}"
#     bin_dir: "{{ bin_dir }}"
#     chart_src: "{{ grayskull_dir }}/{{ helm_metricbeat_image_name }}"
#     chart_version: "{{ helm_metricbeat_chart_version }}"
#     state: absent

#---- Copy over the templates to be used with kubectl delete -f. 
- name: ELK | Templates list
  set_fact:
    elk_role_templates:
      - { file: elk-namespace.yml }
      - { file: elk-certificate.yml }

- name: ELK | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ elk_role_templates }}"
  register: elk_role_manifests

- name: ELK | Remove manifest products
  kube:
    namespace: "{{ elk_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "absent"
  with_items: "{{ elk_role_manifests.results }}"

- name: ELK | Delete subfolder
  file:
    path: "{{ role_dir }}"
    state: absent