---
- name: Prometheus | Download chart
  shell: "{{ bin_dir }}/helm fetch \
    --version {{ helm_prometheus_chart_version }} \
    --destination {{ role_dir }} \
    --untar \
    {{ helm_prometheus_chart_type}}/{{ helm_prometheus_image_name }}"  