---
- name: Prometheus | Templates list
  set_fact:
    prometheus_role_templates:
      - { file: prometheus-namespace.yml }
      - { file: prometheus-crd-clusterrole.yml }
      - { file: prometheus-certificate.yml }

- name: Prometheus | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Prometheus | Template values
  template:
    src: "prometheus-values.yml"
    dest: "{{ role_dir }}/prometheus-values.yml"
    
- name: Prometheus | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ prometheus_role_templates }}"
  register: prometheus_role_manifests

# Namespace must be deployed before secret.
- name: Prometheus | Apply manifests
  kube:
    namespace: "{{ prometheus_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ prometheus_role_manifests.results }}"

- name: Prometheus | Deploy chart
  helm_chart:
    name: "{{ helm_prometheus_chart_name }}"
    namespace: "{{ prometheus_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ role_dir }}/{{ helm_prometheus_image_name }}"
    chart_version: "{{ helm_prometheus_chart_version }}"
    path_to_values: "{{ role_dir }}/prometheus-values.yml"
