---
- name: Prometheus | Templates list
  set_fact:
    prometheus_role_templates:
      - { name: namespace, file: prometheus-namespace.yml, type: ns }
      - { name: cluster-role, file: prometheus-crd-clusterrole.yml, type: ClusterRole }

- name: Setup | Create grayskull directory
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: directory
    mode: '0755'

- name: Prometheus | Template values
  template:
    src: "prometheus-values.yml"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/prometheus-values.yml"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Prometheus | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.file }}"
  with_items: "{{ prometheus_role_templates }}"
  register: prometheus_role_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

# Namespace must be deployed before secret.
- name: Prometheus | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ prometheus_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ prometheus_role_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]


#---- Create secret
- name: Prometheus | Check for secret
  shell: "{{ bin_dir }}/kubectl get secrets -n {{ prometheus_namespace }}"
  register: prometheus_secret_exists
  changed_when: false

- name: Prometheus | Create secret
  shell: "{{ bin_dir }}/kubectl create secret generic {{ ingress_secretName }} --from-file {{ ingress_tls_cert }} --from-file {{ ingress_tls_key }} -n {{ prometheus_namespace }}"
  when: "ingress_secretName not in prometheus_secret_exists.stdout"

- name: Prometheus | Deploy chart
  helm_chart:
    name: "{{ helm_prometheus_chart_name }}"
    namespace: "{{ prometheus_namespace }}"
    bin_dir: "{{ bin_dir }}"
    chart_src: "{{ grayskull_dir }}/{{ helm_prometheus_image_name }}"
    chart_version: "{{ helm_prometheus_chart_version }}"
    path_to_values: "{{ grayskull_dir }}/{{ subfolder }}/prometheus-values.yml"
