---
- name: "Swarm | Template list"
  set_fact:
    swarm_templates:
      - { name: docker-service, file: docker.service, location: /usr/lib/systemd/system }
  when: inventory_hostname in groups['swarm-master']
        
- name: "Swarm | Configure Docker"
  template:
    src: "{{ item.file}}.j2"
    dest: "{{ item.location }}/{{ item.file }}"
  with_items: "{{ swarm_templates }}"
  register: swarm_files
  when: inventory_hostname in groups['swarm-master']

- name: "Swarm | Restart docker daemon"
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: inventory_hostname in groups['swarm-master']

- name: "Swarm | Initialize Primary Master"
  docker_swarm:
    state: present
    listen_addr: "{{ swarm_listen_host }}:{{ swarm_listen_port }}"
  register: swarm_info
  when: inventory_hostname == groups['swarm-master'][0]

- name: "Swarm | Join Tokens"
  set_fact: 
    swarm_join_token_manager: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    swarm_join_token_worker: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    swarm_manager_advertise_addr: "{{ ansible_default_ipv4.address }}"
    swarm_manager_remote_addr: "{{ ansible_default_ipv4.address }}"
    swarm_listen_port: "{{ swarm_listen_port }}"
  when: inventory_hostname == groups["swarm-master"][0]

- name: "Swarm | Join Swarm-master"
  docker_swarm:
    state: join
    advertise_addr: "{{ swarm_advertise_interface }}:{{ swarm_listen_port }}"
    join_token: "{{ hostvars[groups['swarm-master'][0]]['swarm_join_token_manager'] }}"
    remote_addrs: [ "{{ hostvars[groups['swarm-master'][0]]['ip'] }}:{{ swarm_listen_port }}" ]
  when: 
    - inventory_hostname in groups["swarm-master"]
    - inventory_hostname != groups["swarm-master"][0]

- name: "Swarm | Join Worker"
  docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['swarm-master'][0]]['swarm_join_token_worker'] }}"
    advertise_addr: "{{ swarm_advertise_interface }}:{{ swarm_listen_port }}"
    remote_addrs: [ "{{ hostvars[groups['swarm-master'][0]]['ip'] }}:{{ swarm_listen_port }}" ]
  when: inventory_hostname in groups["swarm-worker"]
  
