#!/usr/bin/env python3

import subprocess
import json
import pprint
from jinja2 import FileSystemLoader, Environment

templateLoader = FileSystemLoader(searchpath="./")
templateEnv = Environment(loader=templateLoader)
TEMPLATE_FILE = "ssh_config.tpl"
template = templateEnv.get_template(TEMPLATE_FILE)

getJsonCmd = "terraform state pull"
jsonData,_ = subprocess.Popen([getJsonCmd], shell=True, stdout=subprocess.PIPE).communicate()

data = json.loads(jsonData)['resources']

instances = []
resources = list(filter(lambda x: x['type'] == "aws_instance", data))
for resource in resources:
        k8s_type = resource['name']
        for instance in resource['instances']:
            attr = instance['attributes']
            real_type = ""
            if k8s_type == "k8s_worker":
                real_type = "worker"
            if k8s_type == "k8s_master":
                real_type = "master"
            if k8s_type == "rancher":
                real_type = "rancher"
            data = {
                "public_ip": attr['public_ip'],
                "public_dns": attr['public_dns'],
                "private_ip": attr['private_ip'],
                "private_dns": attr['private_dns'],
                "name": attr['tags']['Name'],
                "type": real_type

            }
            instances.append(data)

print(template.render(instances=instances))
