apiVersion: apps/v1
kind: Deployment
metadata:
    name: ldap
    labels:
        app: ldap
spec:
    selector:
        matchLabels:
            app: ldap
    minReadySeconds: 3
    template:
        metadata:
            labels:
                app: ldap
        spec:
            containers:
              - name: ldap
                image: osixia/openldap
                args: ["--copy-service"]
                ports:
                  - containerPort: 389
                    protocol: TCP
                  - containerPort: 636
                    protocol: TCP
                volumeMounts:
                  - name: config-vol
                    mountPath: /container/service/slapd/assets/config/bootstrap/ldif/config.ldif
                    subPath: config.ldif

            volumes:
              - name: config-vol
                configMap:
                    name: ldif
          
---
apiVersion: v1
kind: Service
metadata:
    name: ldap
    labels:
        app: ldap
spec:
    #type: NodePort
    selector:
        app: ldap
    ports:
      - port: 389
        #protocol: UDP
        name: ldap
      - port: 636
        #protocol: UDP
        name: ldaps

---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ldap-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     kubernetes.io/tls-acme: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/server-snippet: |
#       proxy_ssl_verify off;
# spec:
#   tls:
#   - hosts:
#     - ldap.gsp.test
#     secretName: keycloak-gsp-tls
#   rules:
#   - host: ldap.gsp.test
#     http:
#       paths:
#         - path: /
#           backend:
#             serviceName: ldap
#             servicePort: 389

# ---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ldif
data:
  config.ldif: |
    dn: ou=users,dc=example,dc=org
    changetype: add
    objectClass: organizationalUnit
    objectClass: top
    ou: users

    dn: uid=guest,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: Guest
    sn: guest
    givenName: Guest
    mail: guest@example.com
    uid: guest
    userPassword:: e1NTSEF9VkMxcC8rSU95NHFkSWw3a3JnWkFLNkdCdHJZa3U1aUJFM0xSa1E9P
     Q==

    dn: uid=cdruser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: cdruser
    sn: cdruser
    givenName: cdruser
    mail: cdruser@example.com
    uid: cdruser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=goduser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: goduser
    sn: goduser
    givenName: goduser
    mail: goduser@example.com
    uid: goduser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=replicationuser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: replicationuser
    sn: replicationuser
    givenName: replicationuser
    mail: replicationuser@example.com
    uid: replicationuser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=transformuser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: transformuser
    sn: transformuser
    givenName: transformuser
    mail: transformuser@example.com
    uid: transformuser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=platformuser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: platformuser
    sn: platformuser
    givenName: platformuser
    mail: platformuser@example.com
    uid: platformuser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=securityuser,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: securityuser
    sn: securityuser
    givenName: securityuser
    mail: securityuser@example.com
    uid: securityuser
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: lastname.firstname.M.9999594356
    sn: 9999594356
    mail: lastname.firstname.M.9999594356@example.com
    uid: 9999594356
    uid: lastname.firstname.M.9999594356
    userPassword:: e1NTSEF9Rko5SVN3cHVEWnhZS0JROHd1eWdsUVFpUHNJdjVGK3JGYXVaS2c9P
     Q==

    dn: ou=groups,dc=example,dc=org
    changetype: add
    objectClass: organizationalUnit
    objectClass: top
    ou: groups

    dn: uid=admin,ou=users,dc=example,dc=org
    changetype: add
    objectClass: person
    objectClass: organizationalPerson
    objectClass: extensibleObject
    objectClass: top
    cn: admin
    sn: admin
    mail: admin@example.com
    uid: admin
    userPassword:: e1NTSEF9U09qdGdqUGp6Wk9KUVV0UXE3M0krWGRlakcveVIra2FoWGVGRkE9P
     Q==

    dn: cn=cdr-group,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: cdr-group
    description: cdr users
    member: uid=cdruser,ou=users,dc=example,dc=org
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org

    dn: cn=platform-group,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: platform-group
    description: platform users
    member: uid=platformuser,ou=users,dc=example,dc=org
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org

    dn: cn=security-group,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: security-group
    description: security users
    member: uid=securityuser,ou=users,dc=example,dc=org
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org

    dn: cn=replication-group,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: replication-group
    description: rep users
    member: uid=replicationuser,ou=users,dc=example,dc=org
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org

    dn: cn=transform-group,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: transform-group
    description: transform users
    member: uid=transformuser,ou=users,dc=example,dc=org
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org

    dn: cn=users,ou=groups,dc=example,dc=org
    changetype: add
    objectClass: groupOfNames
    objectClass: top
    cn: users
    description: Users
    member: uid=goduser,ou=users,dc=example,dc=org
    member: uid=platformuser,ou=users,dc=example,dc=org
    member: uid=securityuser,ou=users,dc=example,dc=org
    member: uid=transformuser,ou=users,dc=example,dc=org
    member: uid=cdruser,ou=users,dc=example,dc=org
    member: uid=replicationuser,ou=users,dc=example,dc=org
    member: uid=lastname.firstname.M.9999594356,ou=users,dc=example,dc=org
