- name: Registry | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Registry | Delegate tasks
  when:
    - inventory_hostname == groups['kube-setup-delegate'][0]
  block:
  - name: Registry | Download chart
    shell: "{{ bin_dir }}/helm fetch \
      --repo {{ helm_registry_repo_url }} \
      --version {{ helm_registry_chart_version }} \
      --destination {{ role_dir }} \
      --untar \
      {{ helm_registry_image_name }}"
