- name: Registry | Delegate tasks
  when:
    - inventory_hostname == groups['kube-setup-delegate'][0]
  block:
  - name: Registry | Download chart
    shell: "{{ bin_dir }}/helm fetch \
      --repo {{ helm_registry_repo_url }} \
      --version {{ helm_registry_chart_version }} \
      --destination {{ grayskull_dir }} \
      --untar \
      {{ helm_registry_image_name }}"
