#---- Remove the charts

- name: Registry | remove dockerlogin
  file:
    dest: "~/.docker/config.json"
    state: absent

- name: Certificates | Remove dest dir
  file:
    dest: "{{ ca_path_dest }}"
    state: absent

- name: Registry | Delegate tasks
  when:
    - inventory_hostname == groups['kube-setup-delegate'][0]
  block:
  - name: Registry | Remove chart
    helm_chart:
      name: "{{ helm_registry_chart_name }}"
      namespace: "{{ registry_namespace }}"
      bin_dir: "{{ bin_dir }}"
      chart_src: "{{ grayskull_dir }}/{{ helm_registry_image_name }}"
      chart_version: "{{ helm_registry_chart_version }}"
      state: absent

  # Removing the chart doesn't remove the PVCs. Hopefully finalizers don't get stuck
  - name: Registry | Remove leftover PVCs
    shell: "{{ bin_dir }}/kubectl -n {{ registry_namespace }} delete --all pvc"

  - name: Registry | Templates list
    set_fact:
      registry_role_templates:
        - { file: registry-namespace.yml }
        - { file: registry-certificate.yml }

  - name: Registry | Create subfolder
    file:
      path: "{{ role_dir }}"
      state: directory
      mode: '0755'

  - name: Registry | Create manifests
    template:
      src: "{{ item.file }}"
      dest: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.file }}"
    with_items: "{{ registry_role_templates }}"
    register: registry_role_manifests

  # Namespace must be deployed before secret.
  - name: Registry | Remove manifests
    kube:
      namespace: "{{ registry_namespace }}"
      kubectl: "{{ bin_dir }}/kubectl"
      filename: "{{ role_dir }}/{{ item.item.file }}"
      state: "absent"
    with_items: "{{ registry_role_manifests.results }}"

  - name: Registry | Delete subfolder
    file:
      path: "{{ role_dir }}"
      state: absent