#---- Remove the charts

- name: Registry | remove dockerlogin
  file:
    dest: "~/.docker/config.json"
    state: absent

- name: Certificates | Remove dest dir
  file:
    dest: "{{ ca_path_dest }}"
    state: absent

- name: Registry | Delegate tasks
  when:
    - inventory_hostname == groups['kube-setup-delegate'][0]
  block:
  - name: Registry | Remove chart
    helm_chart:
      name: "{{ helm_registry_name }}"
      namespace: "{{ registry_namespace }}"
      bin_dir: "{{ bin_dir }}"
      chart_src: harbor/harbor
      chart_version: 1.2.0
      state: absent

  # Removing the chart doesn't remove the PVCs. Hopefully finalizers don't get stuck
  - name: Registry | Remove leftover PVCs
    shell: "{{ bin_dir }}/kubectl -n {{ registry_namespace }} delete --all pvc"

  - name: Registry | Templates list
    set_fact:
      registry_role_templates:
        - { name: namespace, file: registry-namespace.yml, type: ns }

  - name: Registry | Create subfolder
    file:
      path: "{{ grayskull_dir }}/{{ subfolder }}"
      state: directory
      mode: '0755'

  - name: Registry | Create manifests
    template:
      src: "{{ item.file }}"
      dest: "{{ grayskull_dir }}//{{ subfolder }}/{{ item.file }}"
    with_items: "{{ registry_role_templates }}"
    register: registry_role_manifests

  - name: Registry | Check for secret
    shell: "{{ bin_dir }}/kubectl get secrets -n {{ registry_namespace }}"
    register: registry_secret_exists
    changed_when: false

  - name: Registry | Remove secret
    shell: "{{ bin_dir }}/kubectl delete secret {{ ingress_secretName }} -n {{ registry_namespace }}"
    when: "ingress_secretName in registry_secret_exists.stdout"

  # Namespace must be deployed before secret.
  - name: Registry | Remove manifests
    kube:
      name: "{{ item.item.name }}"
      namespace: "{{ registry_namespace }}"
      kubectl: "{{ bin_dir }}/kubectl"
      resource: "{{ item.item.type }}"
      filename: "{{ grayskull_dir }}//{{ subfolder }}/{{ item.item.file }}"
      state: "absent"
    with_items: "{{ registry_role_manifests.results }}"

  - name: Registry | Delete subfolder
    file:
      path: "{{ grayskull_dir }}/{{ subfolder }}"
      state: absent

