apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "{{ helm_prometheus_chart_name }}"
  namespace: "{{ prometheus_namespace }}"
spec:
  releaseName: "{{ helm_prometheus_chart_name }}"
  chart:
    repository: "{{ helm_prometheus_repo_url }}"
    name: "{{ helm_prometheus_image_name }}"
    version: "{{ helm_prometheus_chart_version }}"
  values:
{{values}}