apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elk-cert
  namespace: {{ elk_namespace }}
spec:
  secretName: {{ ingress_secretName }}
  issuerRef:
    name: {{ grayskull_ca_issuer_name }}
    kind: ClusterIssuer
  dnsNames:
    - kibana.{{ grayskull_domain }}
