elasticsearchHosts: "http://elasticsearch-master:9200"   

ingress:
  enabled: true
  path: /
  hosts: 
    - "kibana.{{ grayskull_domain }}"
  tls:
    - hosts:
        - "kibana.{{ grayskull_domain }}"
      secretName: elk-gsp-tls
