 service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: syslog
      port: 1514
      targetPort: 1514

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline: 
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
# Delete above line to remove uptime spam from elasticsearch logs.

  input.conf: |-
    input {
      exec { command => "uptime" interval => 30 }

      tcp {
        port => 1514
        codec => json_lines
      }
      # beats {
      #   port => 5044
      # }
    }

  filters.conf: |-
    filter {
      if [app_name] {
        mutate { add_field => { "[@metadata][index]" => "%{[app_name]}" } }
      } else {
        mutate { add_field => { "[@metadata][index]" => "logstash" } }
      }
    }

  outputs.conf: |-
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        manage_template => false
        index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
      }
    }
