---
- name: Ion | Create subfolder
  file:
    path: "{{ role_dir }}"
    state: directory
    mode: '0755'

- name: Ion | Templates list
  set_fact:
    ion_role_templates:
      - { file: ion-namespace.yml }
      - { file: ion-rolebinding.yml }

- name: Ion | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ role_dir }}/{{ item.file }}"
  with_items: "{{ ion_role_templates }}"
  register: ion_role_manifests

# Namespace must be deployed before secret.
- name: Ion | Apply manifests
  kube:
    namespace: "{{ ion_ms_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ role_dir }}/{{ item.item.file }}"
    state: latest
  with_items: "{{ ion_role_manifests.results }}"