- name: Ion | Create subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: directory
    mode: '0755'

- name: Ion | Templates list
  set_fact:
    ion_role_templates:
      - { name: namespace, file: ion-namespace.yml, type: ns }
      - { name: rolebinding, file: ion-rolebinding.yml, type: RoleBinding }

- name: Ion | Create manifests
  template:
    src: "{{ item.file }}"
    dest: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.file }}"
  with_items: "{{ ion_role_templates }}"
  register: ion_role_manifests

- name: Ion | Remove manifest products
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ ion_ms_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ grayskull_dir }}/{{ subfolder }}/{{ item.item.file }}"
    state: absent
  with_items: "{{ ion_role_manifests.results }}"

- name: Ion | Delete subfolder
  file:
    path: "{{ grayskull_dir }}/{{ subfolder }}"
    state: absent