apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "{{ helm_elasticsearch_chart_name }}"
  namespace: "{{ elk_namespace }}"
spec:
  releaseName: "{{ helm_elasticsearch_chart_name }}"
  chart:
    repository: "{{ helm_elasticsearch_repo_url }}"
    name: "{{ helm_elasticsearch_image_name }}"
    version: "{{ helm_elasticsearch_chart_version }}"
  values:
{{elasticsearch_values}}