controller:
  config:
    proxy-buffer-size: "64k"
  hostNetwork: true 
  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostPort: true
  service:
    omitClusterIP: true

  kind: DaemonSet
      
  stats:
    enabled: true
    service:
      omitClusterIP: true

  metrics:
    enabled: true
    service:
      omitClusterIP: true

rbac:
  create: true

defaultBackend:
  service:
    omitClusterIP: true