controller:
  config:
    proxy-buffer-size: "64k"
  hostNetwork: true 
  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostPort: true
  service:
    omitClusterIP: true

  kind: DaemonSet

  # We want the ingress running on all nodes
  tolerations:
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: NoSchedule
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: NoExecute
      
  stats:
    enabled: true
    service:
      omitClusterIP: true

  metrics:
    enabled: true
    service:
      omitClusterIP: true

rbac:
  create: true

defaultBackend:
  service:
    omitClusterIP: true