task_modes:
  - download
  - install

cert_manager_namespace: grayskull-cert-manager
gitops_namespace_dir: "{{ gitops_repo_dir }}/namespaces/{{ cert_manager_namespace }}"
gitops_release_dir: "{{ gitops_repo_dir }}/releases/{{ cert_manager_namespace }}"
gitops_workload_dir: "{{ gitops_repo_dir }}/workloads/{{ cert_manager_namespace }}"
# Hacky solution to getting values file into HelmRelease
# Read the values file, template, and indent it. Then assign it to a variable
# When we template the helm release file the contents of this variable will be loaded
values: "{{ lookup('template', 'templates/values.yml') | indent( width=4, first=True ) }}"

subfolder: cert-manager-role
role_dir: "{{ grayskull_dir }}/{{ subfolder }}"

grayskull_ca_issuer_name: grayskull-ca-issuer
grayskull_ca_issuer_secret: grayskull-ca-key-pair
grayskull_ca_path: "{{ grayskull_dir }}/ca"
grayskull_ca_csrjson_src: "{{ grayskull_dir }}/csr.json"

kube_ca_issuer_name: kube-ca-issuer
kube_ca_issuer_secret: kube-ca-key-pair
kube_ca_path: /etc/kubernetes/ssl

helm_cert_manager_chart_name: "{{ platform_prefix }}-cert-manager"
helm_cert_manager_repo_url: https://charts.jetstack.io
helm_cert_manager_image_name: cert-manager
helm_cert_manager_chart_version: v0.12.0
