task_modes:
  - download
  - install

bin_dir: "/usr/local/bin"

cert_manager_namespace: grayskull-cert-manager

helm_cert_manager_chart_name: "{{ platform_prefix }}-cert-manager"
helm_cert_manager_repo_url: https://charts.jetstack.io
helm_cert_manager_image_name: cert-manager
helm_cert_manager_chart_version: v0.12.0
