task_modes:
  - download
  - install

bin_dir: "/usr/local/bin"

cert_manager_namespace: grayskull-cert-manager

grayskull_ca_path: "{{ grayskull_dir }}/ca"
grayskull_ca_csrjson_src: "{{ grayskull_dir }}/csr.json"
kube_ca_path: /etc/kubernetes/ssl

grayskull_ca_issuer_name: grayskull-ca-issuer
grayskull_ca_issuer_secret: grayskull-ca-key-pair
kube_ca_issuer_name: kube-ca-issuer
kube_ca_issuer_secret: kube-ca-key-pair

helm_cert_manager_chart_name: "{{ platform_prefix }}-cert-manager"
helm_cert_manager_repo_url: https://charts.jetstack.io
helm_cert_manager_image_name: cert-manager
helm_cert_manager_chart_version: v0.12.0
