apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: auth-cert
spec:
  secretName: {{ ingress_secretName }}
  issuerRef:
    name: {{ kube_ca_issuer_name }}
    kind: ClusterIssuer
  dnsNames:
    - auth.{{ grayskull_domain }}
